# Generated by Django 3.0.2 on 2020-01-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_auto_20200118_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['first_name']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
