# Generated by Django 3.0.2 on 2020-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_auto_20200123_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clave',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
