# Generated by Django 3.0.2 on 2020-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_client_clave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clave',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
